---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    example:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /example
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    #serviceAccountName: operate-workflow-sa
  dependencies:
    #- name: test-dep
    #  eventSourceName: webhook
    #  eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        #conditions: test-dep
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: whalesay-loop
                arguments:
                  parameters:
                  - name: payload
                    # the value will get overridden by event payload from test-dep
                    # value: [1,2,3,4,5]
                    value: |
                      [
                        {"name": "foo", "content_ids": [1,2,3,4,5]},
                        {"name": "bar", "content_ids": [6,7,8,9,10]},
                      ]
                templates:
                - name: whalesay-loop
                  inputs:
                    parameters:
                    - name: payload
                  steps:
                  - - name: process-ids
                      template: whalesay
                      arguments:
                        parameters:
                        - name: job
                          value: "{{item.name}}"
                        - name: id
                          value: "{{item.content_ids}}"
                      withParam: "{{inputs.parameters.payload}}"
                - name: whalesay
                  inputs:
                    parameters:
                    - name: job
                    - name: content_ids
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["hello world {{inputs.parameters.job}} id: {{inputs.parameters.id}}"]
          #parameters:
          #  - src:
          #      dependencyName: test-dep
          #      dataKey: body.content_id
          #    dest: spec.arguments.parameters.0.value
---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      # Optional, defaults to 3. If it is < 3, set it to 3, that is the minimal requirement.
      replicas: 3
      # Optional, authen strategy, "none" or "token", defaults to "none"
      auth: token