---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: curlrunner
  namespace: argocd
  labels:
    name: curlrunner
spec:
  destination:
    namespace: curlrunner
    name: in-cluster
  project: default
  source:
    path: charts/curlRunner
    repoUrl: https://github.com/smarman85/kindSampleCluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 1
