---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-kustomize 
  namespace: argocd
spec:
  destination:
    namespace: pod-kustomize
    name: in-cluster
  project: default
  source:
    path: charts/kustomize/pods/overlays/qa
    repoURL: https://github.com/smarman85/kindSampleCluster.git
    targetRevision: HEAD
    # kustomize:
    #   images:
    #   - golang:1.20-bullseye
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 1