---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-certificates
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo 
    name: in-cluster
  #project: us-certificates
  project: default
  source:
    path: demo/cron
    repoURL: https://github.com/smarman85/kindSampleCluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
  revisionHistoryLimit: 3
