---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: dex
spec:
  destination:
    namespace: dex
    name: in-cluster
  project: default
  source:
    path: demo/dex/
    repoURL: https://github.com/smarman85/kindSampleCluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2