---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-demo
  namespace: argocd
spec:
  destination:
    namespace: eso-demo
    name: in-cluster
  project: default
  source:
    path: demo/eso/install.yaml
    repoURL: https://github.com/smarman85/infra101.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 1
