---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    name: in-cluster
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.18.1
    helm:
      values: |
        installCRDs: true
        webhook:
          enabled: false
        extraEnv:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: awssm-secret
                key: access-key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: awssm-secret
                key: secret-access-key
          - name: AWS_REGION
            value: us-east-1
          - name: AWS_ENDPOINT_URL
            value: http://localstack.localstack:4566
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2
