---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullapp
  namespace: argocd
spec:
  destination:
    namespace: fullapp
    name: in-cluster
  project: default
  source:
    path: demo/fullApp/overlays/qa
    repoURL: https://github.com/smarman85/kindSampleCluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2