---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set
  namespace: argocd
spec:
  destination:
    namespace: arc-runners
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/gha-runner-scale-set
    repoURL: https://github.com/smarman85/kindSampleCluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  revisionHistoryLimit: 1
