---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  destination:
    namespace: keda
    name: in-cluster
  project: default
  source:
    path: keda
    repoURL: https://github.com/kedacore/charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  revisionHistoryLimit: 2
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: keda
  namespace: argocd
spec:
  description: "keda project"
  sourceRepos:
  - 'balh'
  destinations:
  - namespace: 'keda'
    server: https://kubernetes.default.svc
  - namespace: 'kube-system'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
  roles:
  orphanedResources:
    warn: true
