---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-server
  namespace: argocd
spec:
  destination:
    namespace: prom
    name: in-cluster
  project: default
  source:
    path: demo/prom-metrics
    repoURL: https://github.com/smarman85/kindSampleCluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2
