---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret
  namespace: sealed-secret
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demo/shared-secret
    repoURL: https://github.com/smarman85/kindSampleCluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 1