---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver-aws-addon
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    name: in-cluster
  project: default
  source:
    path: charts/secrets-store-csi-driver-aws-addon
    repoURL: https://github.com/smarman85/kindSampleCluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2