apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma-service
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma-service
  project: default
  source: 
    path: charts/uptime-test-app
    repoURL: https://github.com/smarman85/kindSampleCluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 2