---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: swissarmyknife-role
  namespace: swissarmyknife
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflowtemplates
  - cronworkflows
  - clusterworkflowtemplates
  - workflowtaskresult
  verbs:
  - '*'