---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: swissarmyknife-rb
  namespace: swissarmyknife
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: swissarmyknife-role
subjects:
- kind: ServiceAccount
  name: swissarmyknife-account
---