---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: php-apache-scaledobject
  namespace: php-apache
spec:
  scaleTargetRef:
    name: php-apache
  triggers:
  - type: cpu
    metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
    metadata:
      value: "50"