---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceAccount.yaml
- deployment.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
  - envs:
      - envVars.yaml
    name: env-vars
    namespace: fullapp