---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-service
  namespace: uptime-kuma
spec:
  # selector tells Kubernetes what Deployment this Service
  # belongs to
  selector:
    app: uptime-kuma
  ports:
  - port: 80
    name: http-port
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  # using the selector, we will expose the running deployments
  # this is how Kubernetes knows, that a given service belongs to a deployment
  selector:
    matchLabels:
      app: uptime-kuma
  replicas: 1
  template:
    metadata:
      labels:
        app: uptime-kuma
        repo: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma-main
        image: localhost/statusreport-test-svc:latest
        imagePullPolicy: Always
        tty: true
        stdin: true
        command: ["/bin/bash"]
        ports:
        - containerPort: 8080