---
apiVersion: v1
kind: Secret
metadata:
  name: rmq-secret
data:
  password: cGFzc3dvcmQ= # hit it's 'password'
  amqpString: YW1xcDovL3VzZXI6cGFzc3dvcmRAcm1xLXN2Yy5zdmM6NTY3Mg== # local testing only
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
spec:
  secretTargetRef:
    - parameter: amqpString
      name: rmq-secret
      key: amqpString
---
apiVersion: v1
kind: Service
metadata:
  name: rmq-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5672
  selector:
    app: rmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq
  labels:
    app: rmq
spec:
  selector:
    matchLabels:
      app: rmq
  template:
    metadata:
      labels:
        app: rmq
    spec:
      containers:
      - name: rmq
        image: rabbitmq:4.0.2
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: user 
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rmq-secret 
              key: password
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
spec:
  scaleTargetRef:
    name: rmq-go
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: hello
      mode: QueueLength
      value: "4"
      hostFromEnv: DB_STRING
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-go
spec:
  selector:
    matchLabels:
      app: rmq-go
  template:
    metadata:
      labels:
        app: rmq-go
    spec:
      containers:
      - name: rmq-go
        image: golang:1.23-bookworm
        tty: true
        stdin: true
        command: ["/bin/bash"]
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: user 
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rmq-secret 
              key: password
        - name: DB_STRING
          valueFrom:
            secretKeyRef:
              name: rmq-secret 
              key: amqpString
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m