---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: csi-driver-secrets
spec:
  parameters:
    objects: |
      - objectName: "qa/csi-driver-deploy/creds"
        objectType: "secretsmanager"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-driver-deploy
spec:
  selector:
    matchLabels:
      app: csi-driver-deploy
  template:
    metadata:
      labels:
        app: csi-driver-deploy
    spec:
      containers:
      - name: csi-driver
        image: golang:1.20-bullseye
        tty: true
        stdin: true
        command: ["/bin/sh"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: secret-store
          mountPath: /mnt/secrets-store
          readOnly: true
      volumes:
        - name: secret-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: csi-driver-secrets