---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fake-it
  namespace: csi-driver-demo
  annotations:
    eks.amazonaws.com/role-arn: ""  # Empty string bypasses IRSA check
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: csi-driver-secrets
spec:
  provider: aws
  parameters:
    awsEndpoint: "http://localstack:localstack:4566"
    objects: |
      - objectName: "qa/csi-driver-deploy/creds"
        objectType: "secretsmanager"
    roleArn: "" # Empty string bypasses IRSA check
    region: "us-east-1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-driver-deploy
spec:
  selector:
    matchLabels:
      app: csi-driver-deploy
  template:
    metadata:
      labels:
        app: csi-driver-deploy
    spec:
      serviceAccountName: fake-it
      containers:
      - name: csi-driver
        env:
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_ACCESS_KEY_ID
          value: "ZHVtbXktYWNjZXNzLWtleQ==" # Required. fake creds for localstack
        - name: AWS_SECRET_ACCESS_KEY 
          value: "ZHVtbXktc2VjcmV0LWtleQ==" # Required. fake creds for localstack
        - name: AWS_SESSION_TOKEN
          value: "ZHVtbXktc2VjcmV0LWtleQ==" # Required. fake creds for localstack
        - name: AWS_ENDPOINT_URL
          value: "http://localstack:localstack:4566" # Localstack endpoint
        image: golang:1.20-bullseye
        tty: true
        stdin: true
        command: ["/bin/sh"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: secret-store
          mountPath: /mnt/secrets-store
          readOnly: true
      volumes:
        - name: secret-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: csi-driver-secrets