---
apiVersion: v1
kind: Secret
metadata:
  name: test-secrets
  namespace: php-apache
data:
  AWS_ACCESS_KEY_ID: "ZHVtbXktYWNjZXNzLWtleQ==" # Required. fake creds for localstack
  AWS_SECRET_ACCESS_KEY: "ZHVtbXktc2VjcmV0LWtleQ==" # Required. fake creds for localstack
  AWS_SESSION_TOKEN: "ZHVtbXktc2VjcmV0LWtleQ=="
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: php-apache
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID     # Required.
    name: test-secrets            # Required.
    key: AWS_ACCESS_KEY_ID        # Required.
  - parameter: awsSecretAccessKey # Required.
    name: test-secrets            # Required.
    key: AWS_SECRET_ACCESS_KEY    # Required.
  - parameter: awsSessionToken    # Required when using temporary credentials.
    name: test-secrets            # Required when using temporary credentials.
    key: AWS_SESSION_TOKEN        # Required when using temporary credentials.
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: php-apache-sqs-queue
  namespace: php-apache
spec:
  scaleTargetRef:
    name: php-apache
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      queueURL: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/localstack-queue"
      queueLength: "3"
      awsRegion: "us-east-1"
      awsEndpoint: "http://localstack.localstack:4566"
