---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  namespace: curlrunner
spec:
  # selector tells Kubernetes what Deployment this Service
  # belongs to
  selector:
    app: curlrunner-app1
  ports:
  - port: 80
    name: http-port
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc2
  namespace: curlrunner
spec:
  # selector tells Kubernetes what Deployment this Service
  # belongs to
  selector:
    app: curlrunner-app2
  ports:
  - port: 80
    name: http-port
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curlrunner-app1
  namespace: curlrunner
spec:
  selector:
    matchLabels:
      app: curlrunner-app1
  replicas: 1
  template:
    metadata:
      labels:
        app: curlrunner-app1
        repo: curlrunner
    spec:
      containers:
      - name: app1
        image: golang:1.20-bullseye
        tty: true
        stdin: true
        command: ["/bin/bash"]
        ports:
        - containerPort: 8080
        env:
          - name: SERVICE_NAME
            value: service1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curlrunner-app2
  namespace: curlrunner
spec:
  selector:
    matchLabels:
      app: curlrunner-app2
  replicas: 1
  template:
    metadata:
      labels:
        app: curlrunner-app2
        repo: curlrunner
    spec:
      containers:
      - name: app2
        image: golang:1.20-bullseye
        tty: true
        stdin: true
        command: ["/bin/bash"]
        ports:
        - containerPort: 8080
        env:
          - name: SERVICE_NAME
            value: service2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  namespace: curlrunner
spec:
  selector:
    matchLabels:
      app: runner
  replicas: 1
  template:
    metadata:
      labels:
        app: runner
        repo: curlrunner
    spec:
      containers:
      - name: runner
        image: golang:1.20-bullseye
        tty: true
        stdin: true
        command: ["/bin/bash"]
        ports:
        - containerPort: 8080
        env:
          - name: SERVICE_NAME
            value: runner
