---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: psql-scaler
  namespace: psql-scaler
spec:
  scaleTargetRef:
    name: php-apache
  pollingInterval: 10   # Optional. Default: 30 seconds
  cooldownPeriod: 30    # Optional. Default: 300 seconds
  maxReplicaCount: 10   # Optional. Default: 100
  triggers:
    - type: postgresql
      metadata:
        userName: postgres
        password: postgres
        host: psql-scaler
        dbName: dvdrental
        port: "5432"
        query: "SELECT COUNT(*) FROM triggers WHERE status='pending';"
        targetQueryValue: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: psql-scaler
  namespace: psql-scaler
  labels:
    run: psql-host
spec:
  ports:
  - port: 5432
  selector:
    run: psql-host